import Head from "next/head";
import Header from "components/Header";
import Hero from "components/Services/webdesign/Hero";
import Intro from "@/components/Services/webdesign/Intro";

export default function webdesign() {
  return (
    <>
      <Head>
        <title>Webdesign - Sawix Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>
        <Header />
        <main>
          <section>
            <Hero />
          </section>
          <section>
            <Intro />
          </section>
        </main>
      </div>
    </>
  );
}
