import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";

export default function socialMediaMarketing() {
  return (
    <>
      <Head>
        <title>Social Media Marketing - Sawix Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <main>
        <section></section>
      </main>
      <Footer />
    </>
  );
}
