import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Header from "../components/Header";
import Hero from "@/components/Hero";
import Portfolio from "@/components/Portfolio";
import About from "@/components/About";
import Services from "@/components/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Sawix Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      <main>
        {/* Hero */}
        <section>
          <Hero />
        </section>

        {/* Portfolio */}
        <section>
          <Portfolio />
        </section>

        {/* About */}
        <section>
          <About />
        </section>

        {/* Services */}
        <section>
          <Services />
        </section>

        {/* Jobs */}

        {/* Footer */}
      </main>
    </>
  );
}
